on:
  push:
    branches:
      - master
      - workshop/*
      - housekeeping/*
      - issue/*
      - dependabot/**
name: "Porsche Accessibility Workshop"
jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Install"
        env:
          PORSCHE_NPM_REGISTRY_TOKEN: ${{ secrets.PORSCHE_NPM_REGISTRY_TOKEN }}
        run: ./.github/scripts/bin/run-install
      - name: "Build"
        run: ./.github/scripts/bin/run-build
      - name: "Store build artifact"
        uses: actions/upload-artifact@v2
        with:
          name: kitchen-sink-build
          path: ./build
  deployment:
    name: "Deployment"
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - name: "Restore build artifact"
        uses: actions/download-artifact@v2
        with:
          name: kitchen-sink-build
          path: ./build
      - name: "Extract branch name"
        if: github.event_name != 'pull_request'
        run: ./.github/scripts/bin/run-branch
      - name: "Deploy 🚀"
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: ./build
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          target-folder: ${{ env.BRANCH_NAME }}
